name: Build and Package Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}   # Pass the token to the job environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

      # Uncomment if you want to run tests
      # - name: Run tests
      #   run: npm run test --if-present

      - name: Build and Package Electron App
        run: npm run ci

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: release-builds/
